services:
  mysql:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
    env_file:
      - .env
  app:
    build:
      context: .
    volumes:
      - ./backend:/sellcars
    restart: on-failure
    command: >
      sh -c "java -jar sellcars.jar"

  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./client:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf